pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Denforcer.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    archiveArtifacts artifacts: '**/*.xml',
                   allowEmptyArchive: true,
                   fingerprint: true,
                   onlyIfSuccessful: true
                }
            }
        }
        stage('Deliver') {
            steps {
                // script {
                //   if (!fileExists("artifacts")) {
                //     sh "mkdir artifacts"
                //   }
                // }
                sh 'touch artifacts/test.txt'
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'artifacts/**/*.txt',
                   allowEmptyArchive: true,
                   fingerprint: true,
                   onlyIfSuccessful: true
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
